#!/usr/bin/env ruby

require 'optparse'

opt = {}
OptionParser.new do |op|
  op.on('-h val', '--height', 'height of the model') { |v| opt[:height] = v.to_i }
  op.on('-w val', '--width', 'width of the model') { |v| opt[:width] = v.to_i }
  op.on('-g', '--gpu', 'use GPU(Cumo)') { |v| opt[:gpu] = v }
  op.parse!(ARGV)
end

require 'cumo/narray' if opt[:gpu]
opt.delete(:gpu)

require 'gray_scott'

module GrayScott
  class << self
    def run(opt)
      xml_path = File.expand_path('../resources/', __dir__)
      Controller.new(xml_path, opt)
      Gtk.main
    end
  end
end

GrayScott.run(opt)
