#!/usr/bin/env ruby

require 'gray_scott'
require 'optparse'

opt = {}
OptionParser.new do |op|
  op.banner += ' msec'
  op.on('-h val', '--height', 'height of the model') { |v| opt[:height] = v.to_i }
  op.on('-w val', '--width', 'width of the model') { |v| opt[:width] = v.to_i }
  op.version = GrayScott::VERSION
  op.parse!(ARGV)
end

if ARGV[0]
  module GrayScott
    MSEC = ARGV[0].to_i
  end
else
  puts 'please specify command-line argument. For example `grayscott 40`'
  exit
end

module GrayScott
  class << self
    def run(opt)
      xml_path = File.expand_path('../resources/', __dir__)
      Controller.new(xml_path, opt)
      Gtk.main
    end
  end
end

GrayScott.run(opt)
